---
apiVersion: eevee.bot/v1alpha1
kind: Toolbox
metadata:
  name: toolbox
  namespace: my-eevee-bot
spec:
  # Number of toolbox replicas to deploy
  size: 1

  # Override container image
  containerImage: ghcr.io/eeveebot/toolbox:latest

  # Override pull policy
  # Defaults to IfNotPresent
  pullPolicy: Always
